name: excel_ai_assistant
description: Excel AI Assistant (Android)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.7
  http: ^1.2.2

flutter:
  uses-material-design: true
